apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
spec:
  selector:
    app: app-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP